service:
  name: markets

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    MARKETS_TABLE_NAME: ${self:custom.MarketsTable.name}
  iamRoleStatements:
    - ${file(iam/MarketsTableIAM.yml):MarketsTableIAM}

resources:
  Resources:
    MarketsTable: ${file(resources/MarketsTable.yml):MarketsTable}

functions:
  createMarket:
    handler: src/handlers/createMarket.handler
    events:
      - http:
          method: POST
          path: /market

custom:
  MarketsTable:
    name: !Ref MarketsTable
    arn: !GetAtt MarketsTable.Arn
